### ISSUE TITLE
eden prevents tfar working properly

### ISSUE THREAD

**Issue by kripto202** [michail-nikolaev/task-force-arma-3-radio#1047]
Any mission that is made in EDEN causes a few issues. It prevents local talk, any advanced mission modules such as switching to the mission channel, doesn't kick in even with the correct information. The only thing that does work is transmitting the message via radio works.

**Comment by michail-nikolaev** [comment]
Hm.. I heard it related to some issues with module placement in eden...

**Comment by kripto202** [comment]
I did put down the advanced tfar module, stating, give tl radio = false, give rifleman radio = false, mission channel = "mission" password = ""

**Comment by jonpas** [comment]
Modules in Eden are broken, reference acemod/ACE3#3339

It has been fixed on dev-branch and BI said in the latest SITREP there will be a hotfix this week.

**Comment by kripto202** [comment]
hotfix came out, can someone check if it has been fixed?

**Comment by kripto202** [comment]
while having ACE 3.4.2, tfar still doesn't work properly after the hotfix

**Comment by jonpas** [comment]
Use ACE 3.5.0, there were fixes. Also make sure to double click on every module and save it again.

**Comment by kripto202** [comment]
alright just need to make sure that the OPTRE compat works in 3.5.0, anything you can tell me to make sure it works?

**Comment by jonpas** [comment]
I don't think OPTRE was merge into ACE3 yet at all.

Also for reference on modules https://github.com/acemod/ACE3/issues/3339#issuecomment-191918087

**Comment by kripto202** [comment]
https://github.com/acemod/ACE3/pull/2925 this is where it's at @jonpas

**Comment by jonpas** [comment]
It's not merged as you see, and t's not part of ACE3 3.5.0.
