### ISSUE TITLE
Transmitting on previous radio when transmitting on new radio

### ISSUE THREAD

**Issue by alexcroox** [michail-nikolaev/task-force-arma-3-radio#1073]
Sorry for the title gore.

I have a SRR and a LRR. SRR is bound to CAPS, LRR is bound to SPACE.

After transmitting on SRR, my next press of SPACE will continue to transmit on SRR. I need to double tab the SPACE key to ensure I transmit on LRR correctly.

This happens every time I alternate transmitting between the 2. This works both ways, switching from LRR to SRR and visa versa. 

It's only ever the first press of the transmit button after transmitting on a different radio/key that is wrong, further presses of the same button transmit on the correct radio (hence the double tap current workaround)

**Comment by michail-nikolaev** [comment]
Try to put LR on space+ ctrl to test.

**Comment by alexcroox** [comment]
I'll give it a go tonight, you think there might be an issue with using a single key for LRR then?

**Comment by michail-nikolaev** [comment]
Yep, probably

**Comment by Hailstorm12** [comment]
I have had this issue since early 2015 and still have this issue even when using a modifier key (CTRL, SHIFT, ALT). It is really annoying for jtacs and especially pilots as there is no intercom system and have to constantly switch between short and long range radios

**Comment by dedmen** [comment]
#845 #954

**Comment by dedmen** [comment]
Gotten worse in current 1.0. Binding LR transmit to Space will cause Space to still start a Transmit on SR and never stop. Some bug in TFAR_fnc_onSwTangentPressedHack. Which has some special handling for LR stuff... Investigating...

**Comment by dedmen** [comment]
WTF is onSwTangentPressedHack even doing? It is doing some wrong isLR check that doesn't even check if that is the LR keybind. and if using the.. Whatever...
Fixed in 3704c9a531fd928a52e185ac1a8af5aa570e2e50
Thanks to @X39 /Arma.Studio and @dedmen /ArmaDebugEngine :3

**Comment by Saborknight** [comment]
I'm afraid this is still an issue. I have a recording of it uploading but it won't show much.

What I noticed was that it often happened when I was using multiple keys at once, not just the radio keys on their own. Things like shift, the AWSD combo. I was essentially moving around a lot whilst using them.

**Comment by dedmen** [comment]
There is a second bug due to how the data is sent to teamspeak.
I already fixed it, but had to revert it again cuz issues

**Comment by SekiAlpha** [comment]
The fix caused an issue where teamspeak will randomly stop picking up any audio from your mic unless you used the radio. IIRC it also broke push to talk.
