### ISSUE TITLE
Radio speakers much too quiet in vehicle

### ISSUE THREAD

**Issue by Knight1981** [michail-nikolaev/task-force-arma-3-radio#1241]
**Arma 3 Version:** `latest stable` (stable / rc / dev)
**CBA Version:** `latest stable` (stable / dev + commit hash)
**Task Force Radio Version:** `1.0-dev.235` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
Speaker in vehicles much too quiet so it is not possible to understand radio call.

**Steps to reproduce:**
1.) Move into vehicle and turn the speaker on (headphones off). 
2.) Receive a radio call from another person.

**Where did the issue occur?**
- Dedicated

**RPT log file:**
not needed

**Comment by dedmen** [comment]
I think I should generally make Vehicle speakers louder. Right now loudness is speaker sett...... Mh... Yeah...
Somehow make Vehicle Speakers generally a little bit louder. As vehicles also have bigger speakers ^^

**Comment by Knight1981** [comment]
Awesome :) Will it be possible to set the volume of the speaker? At the moment it is muuuuch to quiet so please make it much louder, not just "a little bit" :)

**Comment by dedmen** [comment]
You can already set the Speaker Volume by just setting the Volume of the Radio. But I think default setting is 70%.

**Comment by Knight1981** [comment]
ah okay, I thought volume is only the headphone volume. Nice. But yeah, 100% is still much to quiet :)

**Comment by Knight1981** [comment]
Seems that the speakers are now totally broken. If I set the speakers on I can hear them but other players on the dedicated server can't hear it. We tested it several times with some players and different vehicles but we are not able to get it run. We can only hear us on headphones but speakers are not working :(

**Comment by dedmen** [comment]
But they worked in 235? Or what was the last version where they worked?

**Comment by Knight1981** [comment]
We didn't used and tested the speakers in the previous versions because they were much too quiet. In 241 we tested it several times and had that issue which I described in my last post.

Just test it with some people on a dedicated server. Turn on the speaker in different vehicles with different players and try to call them via radio. We used 50Mhz.

**Comment by dedmen** [comment]
Accidentally broke all speakers in 238.
Fixed in 244

**Comment by Knight1981** [comment]
Vielen Dank :) We will check it later.

**Comment by Knight1981** [comment]
Sorry but it still not work Dedmen. It is too quiet and only hearable from the place where the speaker is activated or outsite but not from other seats.

Here you can see a video from our test, maybe it helps:

https://www.twitch.tv/videos/148262537

Kurz nochmal auf deutsch:

Wie Du siehst ist der normale Funk gut zu verstehen direkt zu Beginn im Video aber der Fahrzeug-Funk auf Lautsprecher dagegen viel zu leise. Man hört ihn auch nur auf dem Sitz wo man ihn aktiviert hat, in dem Fall auf dem Fahrersitz. Auf den anderen Plätzen ist er gar nicht zu hören. Außerhalb des Fahrzeugs ist er ganz leise zu hören wenn man direkt daneben steht. Die Lautstärke zu verändern bringt hierbei gar nichts.

**Comment by Knight1981** [comment]
Hey Dedmen. Did you checked our video? Do you need any further information?

**Comment by dedmen** [comment]
No. Have enough information now. Just need time to reproduce it myself.

**Comment by dedmen** [comment]
Problem is that speaker is at vehicle center, so when you are inside of vehicle that might actually be quite far away.

Oh did you report the same in Discord? I fixed a bug report in discord about same thing
https://github.com/michail-nikolaev/task-force-arma-3-radio/commit/0112e7dd101102f14a3e4b15d83459e00b46ddb3

Can you confirm fix?

**Comment by SekiAlpha** [comment]
Confirmed on 1.0.327 with the RHS USAF humvee. The radio is way to quiet at the default radio level.
