### ISSUE TITLE
Using Num-keys with modifier doesn't work for transmit on additional channel.

### ISSUE THREAD

**Issue by Pergor** [michail-nikolaev/task-force-arma-3-radio#1258]
**Arma 3 Version:** `1.68`
**CBA Version:** `3.3.1.170504`
**Task Force Radio Version:** `1.1.0.235`

**Mods:**
- `@CBA_A3`
- `@task_force_radio`

**Description:**
I happen to have transmitting my radios on Num-5 (SR) and Num-8 (LR) - before you wonder, I'm using a Logitech G600 with loads of buttons which are mapped to Num-keys. Before .235 I had the additional transmit mapped to Ctrl-Num-5 and Ctrl-Num-8 respectively. That doesn't work anymore.
Ctrl-Num-5 for regular transmit works fine, just not for the additional channel.
I'm not sure if this is a genuine TFAR problem or a CBA problem though.

**Steps to reproduce:**
Set your controls for SW Transmit Additional to Ctrl-Num-5 and try to transmit -> result is: it doesn't work.
Set your controls for SW Transmit to Ctrl-Num-5 and try to transmit -> result is: it does work.

**Comment by dedmen** [comment]
If it works for Transmit and not for additonal then that's not a CBA problem.. Have to look at that.

**Comment by Pergor** [comment]
If you need additional information, I'm happy to help.

**Comment by Fusselwurm** [comment]
Looks like a problem I have (last tested with 261) – using modifiers wont work for transmitting additional.

**Comment by dedmen** [comment]
https://cdn.discordapp.com/attachments/361498793876783104/361499683002253313/tfar-1.0.262-modifier-fubar.png
>okay, so it seems to me that  I will transmit on "normal" instead of "additional" channel, if the "additional" shortcut is a modified version of the "normal" one…
in this example, I will be able to transmit LR additional when using Shift+P, but when using Shift+ü then just the normal  LR transmit will happen

**Comment by commy2** [comment]
Should be fixed after https://github.com/CBATeam/CBA_A3/pull/686, pls test.

**Comment by Pergor** [comment]
As of CBA-version 3.10.1.190316 and TFAR version 1.0.312 the problem still persists.

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/tree/1.0/addons/core/functions/events/keys
Cause is likely somewhere in the onAdditional
Or in
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/functions/events/keys/fnc_onTangentPressedHack.sqf
Which is specifically aimed to trigger radios with modifiers pressed.

So if you have transmit on T, and alt transmit on shift+T
That code will fire, and ignore the modifier key, and see that you are pressing T which is non-alt transmit.

Frankly it's a bit of a mess. Frankly don't really understand it right now either. It was taken over from 0.9

**Comment by commy2** [comment]
Then nuke this hack and use my improved key handling, which was made after this hack.

**Comment by dedmen** [comment]
Yes cause was in hack.
Hack is still needed for sprinting.

Seems 994c33fe731f4a3fa47c27425b032f17d82b7356 fixed this too.
Tested with CTRL+Numpad 5 as second keybinding for LR Additional.
Works fine when pressing SHIFT+CTRL+NUM5, but not SHIFT+CTRL+W+NUM5 but I think that's my keyboards or armas problem, not the script.

Now I just gotta find out why SW Transmit bind on CTRL+NUM5 also activates LR in my test env... Frick

**Comment by dedmen** [comment]
Derp, it doesn't. CTRL+NUM5 is just the channel switch key for LR
