### ISSUE TITLE
Zeus bug

### ISSUE THREAD

**Issue by tenondra** [michail-nikolaev/task-force-arma-3-radio#1284]
**Arma 3 Version:** `1.71 stable`
**CBA Version:** `3.4.0.170627 stable` 
**Task Force Radio Version:** `1 - 1.0.245  dev`

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- Zeus entity works as a physical entity. Zeus virtual entity has inventory and can even walk, just like normal player. Also the annoying air whistling is still present and hasn't been fixed as you stated previously. Although, Zeus no longer takes damage when falling and can move without problem. Also for some reason TFAR rebinds the default Zeus Y key to Shift+Y. 

**Steps to reproduce:**
1. Place Zeus game master module (do not force interface)
2. Place game master logic and sync them together
3. Spawn as virtual game master logic
4. Experience all those bugs. 

**Where did the issue occur?**
- Dedicated

**Comment by dedmen** [comment]
The shift+Y problem is because we have some key set to default use Y. I thought I fixed that already.
Can you please check in your TFAR hotkey settings which key is bound to Y?

**Comment by tenondra** [comment]
Yeah, you are right. LR was rebinded to Y. But that bug with Zeus is still present. I will try to look at that myself, but since I have never seen the TFAR pbos from inside, it will take me some time.

**Comment by dedmen** [comment]
Some default keybind was on Y. I thought I fixed that already. And it definetly was not LR. Maybe LR Additonal though.

**Comment by tenondra** [comment]
Yeah, sadly not, it still behaves like a character rather than virtual entity.. Not when you switch to Zeus via #adminLogged as normal player, then not even the whistling is here.

**Comment by dedmen** [comment]
I just went into my Zeus Logic mission. I don't have a Inventory and I also cannot move outside of the Zeus Interface.
I also cannot hear a whistling sound. Also I don't fall down. Basically everything behaves as expected.
Are you really only running CBA and TFAR?

**Comment by tenondra** [comment]
with the latest update, this seems to be no longer an issue. 
Weird, for me it was Y by default in 245

**Comment by dedmen** [comment]
246 changed nothing on that :o If it is still default to Y then I still need to change that.

**Comment by tenondra** [comment]
Sadly, can confirm that this hasn't been fixed. Y is obstructed by something by default and thus zeus is still Shift+Y

**Comment by dedmen** [comment]
Are you really really sure that default is Y? You have to manually reset the hotkey to default if it was set to Y before.

**Comment by Arcanum417** [comment]
I am still experienceing the issue with the zeus behaving more like a player than entity... Same steps to replicate on TFAR 1.0.247, even in in single player.

**Comment by dedmen** [comment]
TFAR doesn't work in single player.

**Comment by Arcanum417** [comment]
Sure thing it doesn't work in single player, but the bug is still there, to be clear it also happens in multiplayer and on dedicated server. [SampleMission](https://dl.dropboxusercontent.com/s/h5px99af1zgq1u9/ZeusTFARTest.Stratis.pbo)

**Comment by Arcanum417** [comment]
I am sorry, the mission above works fine for me I found the problem, if the zeus entity respawns (in my test I was using respawnOnStart = 1;) then it behaves like described. I use respawnOnStart in a zeus mission so players dont start on theri placed possion but in the spawn screen where they can choose spawn position. Here is the mission file I can actually replicate the bug [SampleFileFixed](https://dl.dropboxusercontent.com/s/6gst07y6xq5qycy/ZeusTFARTestFixed.Stratis.pbo)

**Comment by Arcanum417** [comment]
Same thing happens if I leave respawnOnStart on 0 and I kill the zeus logic entity somehow (setDamage) and it respawns, after respawn the entity behaves as described in a bugreport.

**Comment by dedmen** [comment]
Sounds alot like it's BI's fault. So you can also access Inventory although the Zeus Entity shouldn't have one? If you respawn in Zeus without TFAR do you also have access to the Inventory? If so it's not TFAR's fault.

**Comment by Arcanum417** [comment]
Yeah, even in vanilla, when you respawn the entity can move, take damage, have inventory....

**Comment by dedmen** [comment]
So....

**Comment by Arcanum417** [comment]
Well, it is Arma issue, but it ddidnt really matter until now, and 0.9.3 works with that just fine... So without this working, a lot of communities just could not use the radio...

**Comment by dedmen** [comment]
0.9.3 ?! That is literally over 3 years old.

**Comment by Arcanum417** [comment]
Sorry my bad, I meant 0.9.12

**Comment by tenondra** [comment]
@dedmen just wanted to ask - has this been fixed in the newer versions?

**Comment by dedmen** [comment]
The default hotkey on Z/Y not yet.

**Comment by dedmen** [comment]
>Also for some reason TFAR rebinds the default Zeus Y key to Shift+Y.

#1431 <--
